### ISSUE TITLE
Pressing back button while updating returns to previous screen

### ISSUE THREAD

**Issue by MitchellQ** [ssm-deepcove/discover_deep_cove#100]
pressing the back button when the app is syncing content allows the user to escape that screen either taking the user back to the previous page on the stack or booting them from the app entirely

we need a way to handle this perhaps just to boot them from the app as the download may continue when the app is in the background (this will require more testing)

**Comment by samuelgrant** [comment]
Is it possible to send them to their previous screen within the app while keeping the download running?

**Comment by jacksos101** [comment]
Navigating the app while data is downloading is likely to cause issues. I'd recommend setting the back button to minimize the app instead.

**Comment by samuelgrant** [comment]
Could we display a popup badge "Content is donwloading, press back again to minimize the app"

**Comment by jacksos101** [comment]
We could.

**Comment by samuelgrant** [comment]
I think it's worth looking at, when I've pressed it during the loading screen it crashes out and that just doesn't quite seem right

**Comment by MitchellQ** [comment]
This issue will be worked on after the CMS integration branch is merged as we are overhauling data sync views etc and this issue may not be an issue.

**Comment by jacksos101** [comment]
I will fix this only if the app cannot be recovered after this happens. 

I.e. if the user does this can they fix the app by running the update again, or is it broken.

**Comment by MitchellQ** [comment]
At this stage this is no longer an issue as we disabled the back button on this view any further changes we make should be separate from this issue
