### ISSUE TITLE
Maintain IDs for data received from CMS

### ISSUE THREAD

**Issue by jacksos101** [ssm-deepcove/discover_deep_cove#110]
For data received from the CMS (ie FactFiles, Tracks, etc), use the IDs supplied, rather than creating new ones. 

This may require adjustments to be made on the CMS.

**Comment by samuelgrant** [comment]
This is especially important as the new API is likely to return APIs for almost everyting when users are looking for updates.

**Comment by jacksos101** [comment]
Turns out that this wasn't actually the issue, and the app was maintaining IDs.
