### ISSUE TITLE
Develop alternate way of recording user images

### ISSUE THREAD

**Issue by jacksos101** [ssm-deepcove/discover_deep_cove#111]
When images are received from the database, we have to keep the IDs persistent, as they will be referred to in other records.

We are currently storing user images in the media files table as well, using auto generated IDs. 

If a user saves photos, and then receives an update with new images added, there is a very high chance of IDs clashing. 

We need to develop a strategy to avoid this. We may need to store user photo information in a different database table.

**Comment by MitchellQ** [comment]
@jacksos101  does that commit resolve this issue?

**Comment by jacksos101** [comment]
Yes
