### ISSUE TITLE
Double check whether an old user photo is deleted when a user takes a new photo

### ISSUE THREAD

**Issue by jacksos101** [ssm-deepcove/discover_deep_cove#126]
When a user replaces the photo for a photo activity that already has a photo, do we delete the original photo file, or does it stay on disk?

We should probably delete.

**Comment by MitchellQ** [comment]
@jacksos101 We should only have one image per photo activity not including if the user selects to save an image to the device.

**Comment by MitchellQ** [comment]
also delete the old tmp photo if the user takes a photo and then either passes or takes another photo

**Comment by MitchellQ** [comment]
Has this been looked at?

**Comment by jacksos101** [comment]
I'm not sure. It will have negligible impact though - how many times will a user change the photo? I reckon we can close this.
