### ISSUE TITLE
Quiz CMS issues

### ISSUE THREAD

**Issue by samuelgrant** [ssm-deepcove/discover_deep_cove#157]
@jacksos101 I need you to verify the following functions are working within the application:
- [ ] Question Shuffle. New installs should shuffle according to the CMS settings. Old applications should continue to function but ignore the shuffle setting
- [ ] If a quizzes questions get updated (ie: a new question gets added or old one removed) delete the quiz high score
- [ ] If I add a unlock code to a quiz, and then update the quizzes on my phone the quiz should dissapare but doesn't.
- [ ] If I change the quiz questions in the CMS the phone doesn't update the quiz
---
Issues identified in test with @MitchellQ: 
- I deleted all active questions in a quiz, but the app never deleted them from the phone. 
- I added questions and they didn't update properly (started throwing client-side errors)

**Comment by jacksos101** [comment]
@MitchellQ Any chance of more detail? I.e. what were the errors?

**Comment by MitchellQ** [comment]
So one issue was at some point for unknown reasons I couldn't connect to the server when refreshing content and i just closed the app so I wouldn't worry about that unless it happens again. The other one was widget is not a subtype of quizquestionbutton I believe no screenshot sorry, however im not sure what lead to it as it happened when sam was updating the quiz and was around the time the connection to the server happened and was resolved when I successful refreshed content im also not worried about this until we get more info @jacksos101

**Comment by jacksos101** [comment]
I believe I've fixed all of these. Except that old applications will need to be reinstalled in order to function.

**Comment by samuelgrant** [comment]
Are we ready for a draft release?

Regards

Samuel Grant
Ph: +64 27 914 8936
E: samueljegrant@outlook.com

230 Talbot Street
Hargest, Invercargill
9810

________________________________

**Comment by MitchellQ** [comment]
@samuelgrant I guess so I will draft a release tonight and then we can figure out if we are ready to release it
