### ISSUE TITLE
Overhaul file sync from server

### ISSUE THREAD

**Issue by jacksos101** [ssm-deepcove/discover_deep_cove#18]
Instead of downloading all files in a zip, app should:

- Request list of required files from server
- Check which files are needed from server
- Request each file from server, one at a time
- Check integrity of each file before storing - retry two times before aborting
- Display progress indications to user
- Check whether any local files are no longer needed, and delete

This will require:

- Adding function to the server to return list of files
- Adding function to the server to return individual file, with hash value
- Reworking app data sync code
- Reworking app UI to display progress indications
- Adding additional API endpoints to the .env file

**Comment by MitchellQ** [comment]
This is in progress at the moment
