### ISSUE TITLE
Prompt user to download content upon fresh install

### ISSUE THREAD

**Issue by jacksos101** [ssm-deepcove/discover_deep_cove#21]
When the application first opens, the user should be prompted to download content if none exists yet.

We could also get the app to check for updates every time it opens, and inform the user that updates are available.

**Comment by MitchellQ** [comment]
Would it not download automatically on first install?   but I agree with the second point

**Comment by jacksos101** [comment]
Users might be on mobile data and not want to download immediately

**Comment by MitchellQ** [comment]
We have decided to download a database upon first install at this stage as the home screen requires data if it has none the app crashes
