### ISSUE TITLE
Noticeboard

### ISSUE THREAD

**Issue by jacksos101** [ssm-deepcove/discover_deep_cove#27]
Thinking back to our meeting with all three of the Deep Cove guys, I remember that they asked for some kind of notifications system.

I think we can implement a noticeboard type set up, where the trust can issue notices through the CMS (online and potentially on-site), and the app will periodically check the server (if it has connection) to see if there are any new notices.

Notices would be simple text messages, and would not contain any media. In the database, they would be stored with an ID, a title, a body, and a timestamp. On the app database, an additional 'viewed' field will be used to determine whether the user has viewed (or acknowledged) the notice. 

It is possible that the app can bring up a dialog box, toast message, snack bar or equivalent when a new notice is detected (or maybe display an icon button somewhere on the screen that doesn't go away until the user taps it and see the notice). This will alert the user of the notice, otherwise they would only know about it if they went to the noticeboard page themselves. Some notices may be important safety announcements, so it is important that they are not missed. Especially for casual visitors who don't have any formal contact with the trust and won't know about recent hazards that have presented themselves.

Notices would be displayed on a view accessed via the 'More' page. The notices would be displayed in a RefreshIndicator widget. This means that the user will be able to swipe the page down to manually refresh notices, in addition to the automatic check mentioned earlier.

A new branch, 'noticeboard' has been created with the intention of developing this feature.

**Comment by samuelgrant** [comment]
Please add another column "type". If a specific priority is set, let's push the notification along with maybe a red ! or something

**Comment by MitchellQ** [comment]
sounds good to me

**Comment by MitchellQ** [comment]
perhaps we can have colors to indicate priority more so than just an exclamation mark (although the text may contain these) i'm thinking the trust can select from either a list of priority (i.e. high, medium etc) or more preferably a list of priority phrases (i.e. High priority, warning, informational) and these would correspond to the bootstrap colors Danger, Warning, Info etc and would have white text this I feel would be more eye catching)

The noticeboard branch has been deleted as it got stale, a new branch will be created when this feature gets implemented

**Comment by samuelgrant** [comment]
@MitchellQ @jacksos101 Please produce a data schema here, and @mention me so I can make an apporpriate ticket on the website repo. . . 

Are you able to render font awesome (or equivalent) icons in the mobile app?

**Comment by jacksos101** [comment]
We do have fontawesome icons available as seen on the [font_awesome_flutter](https://pub.dev/packages/font_awesome_flutter) package. 

Schema would be:

| Type | Name | Constraints |
| ------- | -------- |------------- |
| int    | Id        | PK               |
| bool | Active | required |
| bool | Urgent | required |
| int | ImageId | nullable |
| DateTime | ActivatedAt | required |
| string | Title | required |
| string | ShortDesc | required |
| string | LongDesc | nullable |

Database would hard delete notices.

Admins can disable frequently occuring notification for re-use (e.g. "Caution - flooding on track")

Admins can set the "Urgent" field to true, which will pin the alert to the top of the noticeboard, and display a big warning symbol.

On the main noticeboard page, the notices would display by ActivatedAt, descending (with urgent notices at the top). Display date is set to DateTime.now() when the notice is first created, and upon any subsequent re-activation.

On the main noticeboard page, the following will display for each notice:
- Title 
- ActivatedAt 
- ShortDesc 

On notices with the optional LongDesc filled out, tapping the notice will take the user to a more detailed page, showing:
- Title
- ActivatedAt
- LongDesc
- Image if not null


What do you guys think?

**Comment by MitchellQ** [comment]
That looks good what are your thoughts on my above comment  @jacksos101

**Comment by jacksos101** [comment]
Not a bad idea but bootstrap colors are kind of generic. I think we only need two levels of priority. And I think a big warning symbol, plus being pinned to the top, plus a notification to the user, will be more than enough to make the urgent notice stand out

**Comment by MitchellQ** [comment]
Fair enough

**Comment by jacksos101** [comment]
I mean we can ask the clients tomorrow what they think too

**Comment by jacksos101** [comment]
They might want multiple priorities

**Comment by MitchellQ** [comment]
this is in progress

**Comment by MitchellQ** [comment]
this is resolved in PR #150
