### ISSUE TITLE
Need to implement Informational Activity

### ISSUE THREAD

**Issue by jacksos101** [ssm-deepcove/discover_deep_cove#29]
This activity has not yet had a view built for it.

**Comment by samuelgrant** [comment]
What do you guys think about using fact files for this?

**Use case**:
The fact files are perfect for imparting information on a topic, they have a good picture, text, two headings and sound files. 

If we give the trust the ablity to tag a fact file with a QR code and maybe give them the ability to hdie the fact file from the index page if they want to.
