### ISSUE TITLE
Force Rotation

### ISSUE THREAD

**Issue by MitchellQ** [ssm-deepcove/discover_deep_cove#31]
When implementating rotation we need to force portrait mode on views where will not allow rotation (unless on tablets every view is rotatable)

this is because if the user is in landscape mode and goes to one that is meant to be in portrait mode it will stay in landscape unless forced

**Comment by jacksos101** [comment]
[Potentially relevant](https://github.com/flutter/flutter/issues/13238)

**Comment by MitchellQ** [comment]
At this stage I don't think there is going to be any screen on tablet devices that wont have rotation capabilities so I am going to close this issue
