### ISSUE TITLE
App crashes when setting up the database if there is no previous application files

### ISSUE THREAD

**Issue by MitchellQ** [ssm-deepcove/discover_deep_cove#51]
The error is on the track.dart file 

the SQL error log is "No such table: tracks" the debug exception is 

![image](https://user-images.githubusercontent.com/40969453/62498809-a2c2db00-b834-11e9-8754-91b027de5f59.png)

to reproduce this delete the application files in system storage and run the application

**Comment by jacksos101** [comment]
Okay, I'll get onto this soon

**Comment by jacksos101** [comment]
Workaround for this that you can try in the meantime is to set the settings page as the default page in the Home class, and sync updates before trying to look at the map.

**Comment by MitchellQ** [comment]
There was no settings route in the route generator I presume its the /about trying that didn't work

**Comment by MitchellQ** [comment]
as an aside we should probably rename that

**Comment by jacksos101** [comment]
It's in the home class, not route generator

**Comment by MitchellQ** [comment]
I tried this but had no luck

```
void setLoadingModal({bool isLoading, String loadingMessage, Icon icon}) {

     isLoading = false;
     loadingMessage = "test";
      Icon(Icons.ac_unit);
    }

    switch (settings.name) {
      case '/':
        return MaterialPageRoute(
          // builder: (_) => Home(),
          builder: (_) =>Settings(onProgressUpdate: setLoadingModal,),
        );
```

**Comment by MitchellQ** [comment]
never mind was an emulator problem
