### ISSUE TITLE
App Responsiveness across all devices and tablets

### ISSUE THREAD

**Issue by MitchellQ** [ssm-deepcove/discover_deep_cove#53]
The device needs to be responsive across a range of devices and screen sizes and needs to work on  tablets in landscape mode The devices we are testing on are
#### emulators
- Nexus 5x
- Nexus S
- Nexus 10
#### Physical Devices
- Samsung Galaxy Note 8
- Samsung Galaxy J5 (Sam J)
- Lenovo Tab 37
# Responsiveness
#### Fact File 
- [x] Index
- [x] Details 
- [x] Manual Unlock
#### Map 
- [x] Home
#### Settings
- [x] Settings
- [x] About
#### Quiz 
- [x] Index
- [x] Unlock
- [x] Image Question
- [x] Text Question
- [x] Text only Question
- [x] Result
#### Activities
- [x] Count
- [x] Picture Tap
- [x] Picture Select
- [x] Text
- [x] Photograph
# Landscape
#### Fact File 
- [x] Index
- [x] Details 
- [x] Manual Unlock
#### Map 
- [x] Home
#### Settings
- [x] Settings
- [x] About
#### Quiz 
- [x] Index
- [x] Unlock
- [x] Image Question
- [x] Text Question
- [x] Text only Question
- [x] Result
#### Activities
- [x] Count
- [x] Picture Tap
- [x] Picture Select
- [x] Text
- [x] Photograph

**Comment by samuelgrant** [comment]
Alingment on the "Cecking for Updates" screen is off center. On smaller devices, this was aligned to the left. 

Device type: Vodafone VFD 610

**Comment by MitchellQ** [comment]
This is a known issue it occurs on the initial loading content screen

**Comment by MitchellQ** [comment]
The issue regarding the off center data loading screen has been resolved

**Comment by MitchellQ** [comment]
before the last screen is worked on issue #45 must be resolved
