### ISSUE TITLE
Content labeling

### ISSUE THREAD

**Issue by MitchellQ** [ssm-deepcove/discover_deep_cove#59]
I have deployed a build to an internal track for testing purposes in the pre launch report there are some errors this issue focuses on:

Content labeling 

![image](https://user-images.githubusercontent.com/40969453/62818710-f0c24080-bb9e-11e9-8b17-a253a3a04b79.png)

there are 51 occurrences of this error

more details can be found by logging into the google console selecting the application under the release management drop down select the pre launch report

**Comment by jacksos101** [comment]
Is this something that we are going to worry ourselves with?

**Comment by MitchellQ** [comment]
Not at this stage
