### ISSUE TITLE
Hitting back button not working correctly

### ISSUE THREAD

**Issue by MitchellQ** [ssm-deepcove/discover_deep_cove#60]
Clicking the back button on the fact file details button doesn't  seem to be working  correctly and results in a black screen

**Comment by samuelgrant** [comment]
Hitting the back button here caused the application to crash.

**Comment by jacksos101** [comment]
This was a copy paste error when the fact file overlay was removed. 

`pushReplacementNamed()` was being used instead of `pushNamed()`
