### ISSUE TITLE
Quiz review post completion

### ISSUE THREAD

**Issue by MitchellQ** [ssm-deepcove/discover_deep_cove#62]
After talking with Ethan it would be good if we can have a section that the user can review the questions and their answers or alternatively if we can successfully highlight the correct and incorrect  questions like in the demo application

**Comment by samuelgrant** [comment]
> or alternatively if we can successfully highlight the correct and incorrect questions like in the demo application

The client would like us to keep the system that we have in place now. We can look at adding a "review my awnsers" system. But for now I'm going to drop this to low priority

**Comment by jacksos101** [comment]
Is anyone up for doing this? 

If not, we can close this

**Comment by MitchellQ** [comment]
I think we should close this at this stage
