### ISSUE TITLE
Google Play API password is in source

### ISSUE THREAD

**Issue by jacksos101** [ssm-deepcove/discover_deep_cove#68]
Need to remove sensitive information from source and probably changed the password too, to be safe.

**Comment by jacksos101** [comment]
See #57

**Comment by samuelgrant** [comment]
cc @jacksos101, @MitchellQ - Please investigate methods of removing this from source. Mitchell mentioned the env. Target this for release within 48 hours and change any relevant keys on Google Play at that time as well please.

**Comment by MitchellQ** [comment]
@jacksos101 if you can try add this information into the .env file that would be good thanks

**Comment by jacksos101** [comment]
Just remove the key.properties file from source and update the password:

![image](https://user-images.githubusercontent.com/29448020/63072653-fc37b200-bf78-11e9-8bf3-3b9fa8f23bf5.png)
