### ISSUE TITLE
Consider trying to implement fontSize: size ?? Screen.width(context) <= 350 ? 16 : 20 on text widgets in place of font size 0 see PR #56 for context

### ISSUE THREAD

**Issue by MitchellQ** [ssm-deepcove/discover_deep_cove#72]
This is a minor change that can be attempted if there is time it might make the code easier to read but won't change functionality. It may not work as intended in that I might just end up passing in null instead of 0. we will look into this if we have time

**Comment by jacksos101** [comment]
This has been done in the latest commit to the responsiveness-pictureTapActivity
