### ISSUE TITLE
Add an image to photograph activity if possible

### ISSUE THREAD

**Issue by MitchellQ** [ssm-deepcove/discover_deep_cove#75]
Clients have requested that they would like the ability to have an image included on the photograph activity i.e. so that they can show an image of what an item used to be for example.

**Comment by MitchellQ** [comment]
Im concerned about the available screen real estate on smaller screens, if we have to fit a main image a user image and a description onto a small screen

**Comment by MitchellQ** [comment]
Sam j had a suggestion that we could set up the link to a fact file entry button (this would be hard coded in the CMS) that we had planned in the initial concept this would mean we could direct the user to a specific fact file entry instead of trying to cram an image into views that are already quite full

I think this would be the best way to deal with this issue

**Comment by jacksos101** [comment]
Agreed, lets do that.

**Comment by jacksos101** [comment]
Closing as there is a new issue relating to the solution.
