### ISSUE TITLE
Go through each view on all devices and orientation to confirm ui is up to scratch

### ISSUE THREAD

**Issue by MitchellQ** [ssm-deepcove/discover_deep_cove#76]
When the UI is completed we need to go through each screen in the app including landscape orientation to ensure it is working as expected

perhaps download a few more emulators as well

This will be a chance to make any code improvements as well

**Comment by MitchellQ** [comment]
This issue also encompasses any ui problems found during internal testing

**Comment by MitchellQ** [comment]
decide whether to have the appbars left aligned this may allow more room for text (have more characters before overflow) this might not be needed it may also look better

sample code will be located in a file located in views/noticeboard

**Comment by MitchellQ** [comment]
consider a small tablet method to optimize it for the lenovo

**Comment by jacksos101** [comment]
Consider making large blocks of text an off-white grey, rather than white.

**Comment by MitchellQ** [comment]
consider adding a colour override to the text widgets and making large blocks of text on the charcoal background grey #999999

**Comment by MitchellQ** [comment]
What he said ^^

**Comment by jacksos101** [comment]
Completed. Although this is more of an ongoing thing whenever changes are made, rather than a one off.
