### ISSUE TITLE
Some QR codes cause the app to crash.

### ISSUE THREAD

**Issue by samuelgrant** [ssm-deepcove/discover_deep_cove#77]
Scanning some QR codes causes the application to crash.

Could this be because the QR code is unassigned? Let's add a pop up notification instead.

**Device Types:** `Various`

**QR Code Number:**  `505110 - Invalid` & `050110 - Info2`

**Comment by MitchellQ** [comment]
Info 2 is an informational activity type that doesn't have a view associated with it, see issue #29 invalid qr code scanning handles correctly
