### ISSUE TITLE
Delayed map animation when changing track

### ISSUE THREAD

**Issue by jacksos101** [ssm-deepcove/discover_deep_cove#8]
When changing tracks, the name of the track changes immediately, but the animation is significantly delayed. 

Need to investigate whether this is just Flutter_Map being slow, or if we are using code sub-optimally.

**Comment by jacksos101** [comment]
On my phone, using a release build, the map doesn't even animate for some reason.

**Comment by MitchellQ** [comment]
On my phone running the release version on the combine-code the map animation works perfectly there is maybe a tiny delay but it is significantly improved there is also none of the delays in loading tiles that is an issue on the debug build either

**Comment by jacksos101** [comment]
Yes, but your phone is high end, so it doesn't count :P

We need to target this at cheap phones

**Comment by MitchellQ** [comment]
What difference would that make, apart from better hardware which we can't fix and that really shouldn't affect the library, if it is a phone performance issue then how can we resolve this?

**Comment by MitchellQ** [comment]
So I have a potential fix to your issue where the splash animation stops before the animation is completed this is pushed on combine code and needs to be tested on your device specifically

**Comment by jacksos101** [comment]
Will test this after I have the map working from the database.
