### ISSUE TITLE
Tap accuracy - Picture tap - Landscape

### ISSUE THREAD

**Issue by MitchellQ** [ssm-deepcove/discover_deep_cove#86]
When implementing responsiveness the accuracy of picture tap has decreased this is substanial in landscape mode and needs to be rectified, this is also present in portrait mode (likely due to the image not being in direct contact with the 3 edges (left, right, bottom) of the screen) however this not a breaking error

**Comment by jacksos101** [comment]
Does the location of the circle change when the orientation is changed?

I think this is a mitchell problem :)
