### ISSUE TITLE
Animate to track bounds rather than first activity

### ISSUE THREAD

**Issue by jacksos101** [ssm-deepcove/discover_deep_cove#9]
Might be nice to animate the map so that all activities are in view, rather than going straight to the first activity? I have seen methods for doing this in the Flutter_Map library.

Then again, it might not work very well if activities start grouping together.

**Comment by MitchellQ** [comment]
navigating to the first activity just seemed the easiest / most appropriate thing but as you pointed out that it's not easy if the activities are grouped together case in point in my sample data the brasells point and hanging valley first markers are quite close to  one another so there is not much animation between the points. I had considered taking another point perhaps in the 'center' of the tracks which is either another data point we have to collect or figure a way to calculate that ourselves, unless you have another idea?

**Comment by jacksos101** [comment]
Zoom / animate to bounds

**Comment by MitchellQ** [comment]
This won't be worked on at this time
